name: 'Prepare: Install'
description: 'Prepares the repo by installing dependencies'

runs:
  using: 'composite'
  steps:
    - name: echo github.ref
      shell: bash
      run: echo ${{ github.ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: npm ci
